apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 02-kubelet-env-config-worker
spec:
  config:
    ignition:
      config: {}
      security:
        tls: {}
      timeouts: {}
      version: 2.2.0
    networkd: {}
    passwd: {}
    storage:
      files:
      - contents:
          source: data:text/plain;charset=utf-8;base64,S1VCRUxFVF9MT0dfTEVWRUw9MQo=
          verification: {}
        filesystem: root
        mode: 420
        path: /etc/kubernetes/kubelet-env
  osImageURL: ""
